import { useState } from "react";
import { api } from "../../../api/axios";
import { ENDPOINTS } from "../../../api/endpoints";
import { FaFileAlt, FaCalendarAlt, FaUpload } from "react-icons/fa";

export default function ReportForm() {
  const [form, setForm] = useState({
    generated_by: "",
    donor: "",
    recycling_center: "",
    report_type: "",
    period_from: "",
    period_to: "",
    total_waste_collected: "",
    total_waste_recycled: "",
    generated_date: "",
    report_file: null,
  });

  const onChange = (e) => {
    const { name, value, type, files } = e.target;
    if (type === "file") return setForm({ ...form, [name]: files?.[0] ?? null });
    setForm({ ...form, [name]: value });
  };

  const onSubmit = async (e) => {
    e.preventDefault();

    try {
      const payload = {
        generatedBy: form.generated_by ? Number(form.generated_by) : null,
        donorId: form.donor ? Number(form.donor) : null,
        recyclingCenterId: form.recycling_center ? Number(form.recycling_center) : null,
        reportType: form.report_type,
        periodFrom: form.period_from,
        periodTo: form.period_to,
        totalWasteCollected: form.total_waste_collected,
        totalWasteRecycled: form.total_waste_recycled,
        generatedDate: form.generated_date,
        reportFile: form.report_file ? form.report_file.name : "",
      };

      const res = await api.post(ENDPOINTS.report, payload);

      alert("Report saved");
      console.log(res.data);

      setForm({
        generated_by: "",
        donor: "",
        recycling_center: "",
        report_type: "",
        period_from: "",
        period_to: "",
        total_waste_collected: "",
        total_waste_recycled: "",
        generated_date: "",
        report_file: null,
      });

    } catch (err) {
      console.error(err);
      alert("Save failed");
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>

        {/* HEADER */}
        <div style={styles.header}>
          <FaFileAlt size={26} />
          <h2>Generate Report</h2>
        </div>

        <form onSubmit={onSubmit} style={styles.form}>

          <input name="generated_by" placeholder="Generated By (User ID)" value={form.generated_by} onChange={onChange} style={styles.input} />

          <input name="donor" placeholder="Donor ID" value={form.donor} onChange={onChange} style={styles.input} />

          <input name="recycling_center" placeholder="Recycling Center ID" value={form.recycling_center} onChange={onChange} style={styles.input} />

          <input name="report_type" placeholder="Report Type" value={form.report_type} onChange={onChange} style={styles.input} />

          {/* DATE RANGE */}
          <div style={styles.row}>
            <div style={styles.inputGroup}>
              <FaCalendarAlt />
              <input type="date" name="period_from" value={form.period_from} onChange={onChange} style={styles.input} />
            </div>

            <div style={styles.inputGroup}>
              <FaCalendarAlt />
              <input type="date" name="period_to" value={form.period_to} onChange={onChange} style={styles.input} />
            </div>
          </div>

          <input name="total_waste_collected" placeholder="Total Waste Collected" value={form.total_waste_collected} onChange={onChange} style={styles.input} />

          <input name="total_waste_recycled" placeholder="Total Waste Recycled" value={form.total_waste_recycled} onChange={onChange} style={styles.input} />

          <div style={styles.inputGroup}>
            <FaCalendarAlt />
            <input type="date" name="generated_date" value={form.generated_date} onChange={onChange} style={styles.input} />
          </div>

          {/* FILE */}
          <label style={styles.fileBox}>
            <FaUpload />
            <span>Upload Report File</span>
            <input type="file" name="report_file" onChange={onChange} hidden />
          </label>

          <button type="submit" style={styles.button}>
            Save Report
          </button>

        </form>
      </div>
    </div>
  );
}

const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    marginTop: "40px",
  },
  card: {
    width: "520px",
    padding: "25px",
    borderRadius: "12px",
    background: "#1e293b",
    boxShadow: "0 0 20px rgba(0,0,0,0.5)",
    color: "white",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    justifyContent: "center",
    marginBottom: "20px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "15px",
  },
  row: {
    display: "flex",
    gap: "10px",
  },
  inputGroup: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    background: "#334155",
    padding: "5px",
    borderRadius: "8px",
    flex: 1,
  },
  input: {
    flex: 1,
    padding: "10px",
    borderRadius: "8px",
    border: "none",
    outline: "none",
  },
  fileBox: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    background: "#334155",
    padding: "10px",
    borderRadius: "8px",
    cursor: "pointer",
  },
  button: {
    padding: "10px",
    background: "#38bdf8",
    border: "none",
    borderRadius: "8px",
    fontWeight: "bold",
    cursor: "pointer",
  },
};